import { StyleSheet } from "react-native";
import React from "react";
import { mvs } from "../../config/metrices";

const styles = StyleSheet.create({
  scrollContainer: { backgroundColor: "#fff" },
  detailContainer: {
    alignSelf: "center",
    padding: mvs(4),
    backgroundColor: "#0B6699",
    margin: mvs(5),
    width: "60%",
    borderRadius: mvs(8),
  },
  addressView: { position: "absolute", bottom: 5, right: 0 },
  confirmContainer: {
    width: "90%",
    alignSelf: "center",
    backgroundColor: "#F4F4F4",
    borderRadius: mvs(8),
    borderColor: "#fff",
    borderWidth: mvs(1),
    padding: mvs(5),
    shadowColor: "#000",
    marginTop: mvs(3),
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  priceContainer: {
    backgroundColor: "#05B321",
    padding: mvs(6),
    alignSelf: "flex-end",
    borderRadius: mvs(2),
    borderColor: "#fff",
    borderWidth: mvs(1),
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  patientView: {
    flexDirection: "row",
    marginTop: mvs(5),
    justifyContent: "space-between",
  },
  yesBtn: {
    flexDirection: "row",
    alignItems: "center",
    marginEnd: mvs(20),
  },
  boxStyle: {
    width: mvs(10),
    height: 10,
    borderRadius: mvs(2),
    borderWidth: mvs(1),
    borderColor: "#000",
  },
  btnContainer: {
    marginVertical: mvs(8),
    flexDirection: "row",
    alignSelf: "center",
    alignItems: "flex-end",
    justifyContent: "space-between",
    width: "90%",
  },
  btnFace: {
    paddingVertical: mvs(5),
    paddingHorizontal: mvs(10),
    backgroundColor: "#fff",
    borderRadius: mvs(15),
    borderWidth: mvs(1),
    width: mvs(100),
    borderColor: "#000",
    alignItems: "center",
    justifyContent: "center",
  },
  viewProof: {
    paddingVertical: mvs(10),
    paddingHorizontal: mvs(15),
    backgroundColor: "#0B6699",
    borderRadius: mvs(10),
    alignItems: "center",
    justifyContent: "center",
  },
  signtureContainer: {
    padding: mvs(7),
    width: "90%",
    alignSelf: "center",
    backgroundColor: "#F4F4F4",
    borderRadius: mvs(8),
    borderWidth: mvs(1),
    borderColor: "#fff",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  signBtnContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },

  signBtn: {
    paddingVertical: mvs(5),
    paddingHorizontal: mvs(10),
    backgroundColor: "#fff",
    borderRadius: mvs(5),
    borderWidth: mvs(2),
    borderColor: "#000",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  signImage: {
    width: mvs(25),
    height: mvs(25),
    marginHorizontal: mvs(5),
  },
  captureView: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  imageSent: {
    width: mvs(12),
    height: mvs(12),
    position: "absolute",
    top: 0,
    right: 0,
  },
  imageRead: {
    width: mvs(15),
    height: mvs(15),
    position: "absolute",
    top: 0,
    right: 0,
  },
  imageCapture: {
    width: mvs(25),
    height: mvs(25),
    marginEnd: mvs(20),
    marginHorizontal: mvs(5),
  },
  driveView: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  driveDetail: {
    paddingVertical: mvs(5),
    paddingHorizontal: mvs(10),
    backgroundColor: "#fff",
    borderRadius: mvs(15),
    width: "70%",
    borderWidth: mvs(1),
    borderColor: "#000",
    alignItems: "center",
    justifyContent: "center",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  checkPharmacy: {
    flexDirection: "row",
    alignItems: "center",
    marginEnd: mvs(20),
    justifyContent: "flex-end",
    marginTop: mvs(9),
  },
  contectView: {
    padding: mvs(7),
    width: "90%",
    alignSelf: "center",
    backgroundColor: "#F4F4F4",
    borderRadius: mvs(8),
    marginVertical: mvs(12),
    borderWidth: mvs(1),
    borderColor: "#fff",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  btnView: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    marginVertical: mvs(8),
  },
  btnStyle: {
    paddingVertical: mvs(10),
    width: mvs(120),

    borderRadius: mvs(10),
    alignItems: "center",
    justifyContent: "center",
  },
  reasonView: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-evenly",
    marginBottom: mvs(40),
  },
  reasonContainer: {
    paddingVertical: mvs(5),
    paddingHorizontal: mvs(10),
    backgroundColor: "#fff",
    borderRadius: mvs(15),
    paddingHorizontal: mvs(30),
    borderWidth: mvs(1),
    borderColor: "#000",
    alignItems: "center",
    justifyContent: "center",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  alertView: {
    position: "absolute",
    //flex: 1,
    height: "100%",
    width: "100%",
    justifyContent: "center",
    //alignItems: "center",
    backgroundColor: 'rgba(52, 52, 52, 0.8)',
    paddingHorizontal: mvs(27),
    zIndex: 1,

  }
});

export default styles;
